server:
  port: 3020
  base:
    url: http://127.0.0.1:3020

secure:
  aes:
    key: ngbT^~!=/*)[Ybcg
    
spring:
  dubbo:
    application:
      name: xxpay4dubbo-web
    registry:
      address: zookeeper://47.106.118.9:2181
    scan: org.wlpay.dubbo
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        fixed:
          enabled: true
          paths:
          - /**
          version: v1.0.0

logging:
  file: ./log/xxpay4dubbo-web.log
  

rsa:
  private:
    key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBANA/UT013Wkz9ATkswy1dObtHIlbGouwdZDi7WemP80JfJmz8l6BM1Mcv0NTNgualMkowx1frdVM/hf5/EUa1eO9a9QMRwfLKw4HmR4Z/GjIxUMuoH19RRtUyl5KqbUWQhvmiK4P8SozZNRtGs1966y3891AU1siRjJ9O0F6zyFhAgMBAAECgYBgbEDob61yTcz6Cw7gnpBfcICbFOTosy7shDZanL7D6FWaMZjSq04heJkSyk+m9c9YiRg23Jt3vSuV3HkzYiaQc7iuaYETS4Eg+z2u9cEnDJ451+Pp6sowWF4xpQyzuT44LpxxD+EtN4KU5VAGix3nt7xrQpL8wPt4waB1ARGKJQJBAO1od8qVDa3ntEO5RRvTYX26t1rQqtG78Z2yUC5PZ7LYdyftT/d3ZNWQo7YnIQnafWUQMewMW94FkHGHC0KSptcCQQDgjjzls5cM2dM6Y/4Mwzh+43LLvYSLOUuS6hxf38RII3d34Ug1h0BakNKouG9fjf48Y3Zs1VcfZpcWC4oJ2UqHAkAu5Z4URJFpMwYnAqgmMQFnJsUliWbU+31lG14/Z6wiZiRTnMtZJRqkHWhZiS07lw+CMUrLSD21g//ejUCqK/INAkBZIXwgfJk/G5LRAXGMZUyeaO9e2Vmr3VEW/l/G2k3RiGpaJgyAWq/7grJrD9H9LqI0HBKcfk23hAQCVxAyepIvAkBnmo121SUVnnpfrL0B2omeystYg3abma2M50S2LyYI5Lc8dVzKdLLf9X3cJyserPubpOhF3hhKwTCftDkgxZhO
  public:
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQP1E9Nd1pM/QE5LMMtXTm7RyJWxqLsHWQ4u1npj/NCXyZs/JegTNTHL9DUzYLmpTJKMMdX63VTP4X+fxFGtXjvWvUDEcHyysOB5keGfxoyMVDLqB9fUUbVMpeSqm1FkIb5oiuD/EqM2TUbRrNfeust/PdQFNbIkYyfTtBes8hYQIDAQAB

