server:
  port: 3020

spring:
  dubbo:
    application:
      name: xxpay4dubbo-web
    registry:
      address: zookeeper://47.106.118.9:2181
    scan: org.wlpay.dubbo

logging:
  file: ./log/xxpay4dubbo-web.log